-- GENERATE BY ./scripts/generate.ts
-- DO NOT EDIT IT MANUALLY


module Stories exposing (allCategories)

import Ant.Icons
import Html exposing (Html)
import Svg.Attributes exposing (height, width)


type alias Category msg =
    { name : String
    , outlined : List (Html msg)
    , filled : List (Html msg)
    , twoTone : List (Html msg)
    }


allCategories : List (Category msg)
allCategories =
    [ direction
    , suggestion
    , editor
    , data
    , logo
    , other
    ]


direction : Category msg
direction =
    { name = "Directional Icons"
    , outlined =
        [ Ant.Icons.stepBackwardOutlined [ width "64", height "64" ]
        , Ant.Icons.stepForwardOutlined [ width "64", height "64" ]
        , Ant.Icons.fastBackwardOutlined [ width "64", height "64" ]
        , Ant.Icons.fastForwardOutlined [ width "64", height "64" ]
        , Ant.Icons.shrinkOutlined [ width "64", height "64" ]
        , Ant.Icons.arrowsAltOutlined [ width "64", height "64" ]
        , Ant.Icons.downOutlined [ width "64", height "64" ]
        , Ant.Icons.upOutlined [ width "64", height "64" ]
        , Ant.Icons.leftOutlined [ width "64", height "64" ]
        , Ant.Icons.rightOutlined [ width "64", height "64" ]
        , Ant.Icons.caretUpOutlined [ width "64", height "64" ]
        , Ant.Icons.caretDownOutlined [ width "64", height "64" ]
        , Ant.Icons.caretLeftOutlined [ width "64", height "64" ]
        , Ant.Icons.caretRightOutlined [ width "64", height "64" ]
        , Ant.Icons.upCircleOutlined [ width "64", height "64" ]
        , Ant.Icons.downCircleOutlined [ width "64", height "64" ]
        , Ant.Icons.leftCircleOutlined [ width "64", height "64" ]
        , Ant.Icons.rightCircleOutlined [ width "64", height "64" ]
        , Ant.Icons.doubleRightOutlined [ width "64", height "64" ]
        , Ant.Icons.doubleLeftOutlined [ width "64", height "64" ]
        , Ant.Icons.verticalLeftOutlined [ width "64", height "64" ]
        , Ant.Icons.verticalRightOutlined [ width "64", height "64" ]
        , Ant.Icons.verticalAlignTopOutlined [ width "64", height "64" ]
        , Ant.Icons.verticalAlignMiddleOutlined [ width "64", height "64" ]
        , Ant.Icons.verticalAlignBottomOutlined [ width "64", height "64" ]
        , Ant.Icons.forwardOutlined [ width "64", height "64" ]
        , Ant.Icons.backwardOutlined [ width "64", height "64" ]
        , Ant.Icons.rollbackOutlined [ width "64", height "64" ]
        , Ant.Icons.enterOutlined [ width "64", height "64" ]
        , Ant.Icons.retweetOutlined [ width "64", height "64" ]
        , Ant.Icons.swapOutlined [ width "64", height "64" ]
        , Ant.Icons.swapLeftOutlined [ width "64", height "64" ]
        , Ant.Icons.swapRightOutlined [ width "64", height "64" ]
        , Ant.Icons.arrowUpOutlined [ width "64", height "64" ]
        , Ant.Icons.arrowDownOutlined [ width "64", height "64" ]
        , Ant.Icons.arrowLeftOutlined [ width "64", height "64" ]
        , Ant.Icons.arrowRightOutlined [ width "64", height "64" ]
        , Ant.Icons.playCircleOutlined [ width "64", height "64" ]
        , Ant.Icons.upSquareOutlined [ width "64", height "64" ]
        , Ant.Icons.downSquareOutlined [ width "64", height "64" ]
        , Ant.Icons.leftSquareOutlined [ width "64", height "64" ]
        , Ant.Icons.rightSquareOutlined [ width "64", height "64" ]
        , Ant.Icons.loginOutlined [ width "64", height "64" ]
        , Ant.Icons.logoutOutlined [ width "64", height "64" ]
        , Ant.Icons.menuFoldOutlined [ width "64", height "64" ]
        , Ant.Icons.menuUnfoldOutlined [ width "64", height "64" ]
        , Ant.Icons.borderBottomOutlined [ width "64", height "64" ]
        , Ant.Icons.borderHorizontalOutlined [ width "64", height "64" ]
        , Ant.Icons.borderInnerOutlined [ width "64", height "64" ]
        , Ant.Icons.borderOuterOutlined [ width "64", height "64" ]
        , Ant.Icons.borderLeftOutlined [ width "64", height "64" ]
        , Ant.Icons.borderRightOutlined [ width "64", height "64" ]
        , Ant.Icons.borderTopOutlined [ width "64", height "64" ]
        , Ant.Icons.borderVerticleOutlined [ width "64", height "64" ]
        , Ant.Icons.picCenterOutlined [ width "64", height "64" ]
        , Ant.Icons.picLeftOutlined [ width "64", height "64" ]
        , Ant.Icons.picRightOutlined [ width "64", height "64" ]
        , Ant.Icons.radiusBottomleftOutlined [ width "64", height "64" ]
        , Ant.Icons.radiusBottomrightOutlined [ width "64", height "64" ]
        , Ant.Icons.radiusUpleftOutlined [ width "64", height "64" ]
        , Ant.Icons.radiusUprightOutlined [ width "64", height "64" ]
        , Ant.Icons.fullscreenOutlined [ width "64", height "64" ]
        , Ant.Icons.fullscreenExitOutlined [ width "64", height "64" ]
        ]
    , filled =
        [ Ant.Icons.stepBackwardFilled [ width "64", height "64" ]
        , Ant.Icons.stepForwardFilled [ width "64", height "64" ]
        , Ant.Icons.fastBackwardFilled [ width "64", height "64" ]
        , Ant.Icons.fastForwardFilled [ width "64", height "64" ]
        , Ant.Icons.caretUpFilled [ width "64", height "64" ]
        , Ant.Icons.caretDownFilled [ width "64", height "64" ]
        , Ant.Icons.caretLeftFilled [ width "64", height "64" ]
        , Ant.Icons.caretRightFilled [ width "64", height "64" ]
        , Ant.Icons.upCircleFilled [ width "64", height "64" ]
        , Ant.Icons.downCircleFilled [ width "64", height "64" ]
        , Ant.Icons.leftCircleFilled [ width "64", height "64" ]
        , Ant.Icons.rightCircleFilled [ width "64", height "64" ]
        , Ant.Icons.forwardFilled [ width "64", height "64" ]
        , Ant.Icons.backwardFilled [ width "64", height "64" ]
        , Ant.Icons.playCircleFilled [ width "64", height "64" ]
        , Ant.Icons.upSquareFilled [ width "64", height "64" ]
        , Ant.Icons.downSquareFilled [ width "64", height "64" ]
        , Ant.Icons.leftSquareFilled [ width "64", height "64" ]
        , Ant.Icons.rightSquareFilled [ width "64", height "64" ]
        ]
    , twoTone =
        [ Ant.Icons.upCircleTwoTone [ width "64", height "64" ]
        , Ant.Icons.downCircleTwoTone [ width "64", height "64" ]
        , Ant.Icons.leftCircleTwoTone [ width "64", height "64" ]
        , Ant.Icons.rightCircleTwoTone [ width "64", height "64" ]
        , Ant.Icons.playCircleTwoTone [ width "64", height "64" ]
        , Ant.Icons.upSquareTwoTone [ width "64", height "64" ]
        , Ant.Icons.downSquareTwoTone [ width "64", height "64" ]
        , Ant.Icons.leftSquareTwoTone [ width "64", height "64" ]
        , Ant.Icons.rightSquareTwoTone [ width "64", height "64" ]
        ]
    }


suggestion : Category msg
suggestion =
    { name = "Suggested Icons"
    , outlined =
        [ Ant.Icons.questionOutlined [ width "64", height "64" ]
        , Ant.Icons.questionCircleOutlined [ width "64", height "64" ]
        , Ant.Icons.plusOutlined [ width "64", height "64" ]
        , Ant.Icons.plusCircleOutlined [ width "64", height "64" ]
        , Ant.Icons.pauseOutlined [ width "64", height "64" ]
        , Ant.Icons.pauseCircleOutlined [ width "64", height "64" ]
        , Ant.Icons.minusOutlined [ width "64", height "64" ]
        , Ant.Icons.minusCircleOutlined [ width "64", height "64" ]
        , Ant.Icons.plusSquareOutlined [ width "64", height "64" ]
        , Ant.Icons.minusSquareOutlined [ width "64", height "64" ]
        , Ant.Icons.infoOutlined [ width "64", height "64" ]
        , Ant.Icons.infoCircleOutlined [ width "64", height "64" ]
        , Ant.Icons.exclamationOutlined [ width "64", height "64" ]
        , Ant.Icons.exclamationCircleOutlined [ width "64", height "64" ]
        , Ant.Icons.closeOutlined [ width "64", height "64" ]
        , Ant.Icons.closeCircleOutlined [ width "64", height "64" ]
        , Ant.Icons.closeSquareOutlined [ width "64", height "64" ]
        , Ant.Icons.checkOutlined [ width "64", height "64" ]
        , Ant.Icons.checkCircleOutlined [ width "64", height "64" ]
        , Ant.Icons.checkSquareOutlined [ width "64", height "64" ]
        , Ant.Icons.clockCircleOutlined [ width "64", height "64" ]
        , Ant.Icons.warningOutlined [ width "64", height "64" ]
        , Ant.Icons.issuesCloseOutlined [ width "64", height "64" ]
        , Ant.Icons.stopOutlined [ width "64", height "64" ]
        ]
    , filled =
        [ Ant.Icons.questionCircleFilled [ width "64", height "64" ]
        , Ant.Icons.plusCircleFilled [ width "64", height "64" ]
        , Ant.Icons.pauseCircleFilled [ width "64", height "64" ]
        , Ant.Icons.minusCircleFilled [ width "64", height "64" ]
        , Ant.Icons.plusSquareFilled [ width "64", height "64" ]
        , Ant.Icons.minusSquareFilled [ width "64", height "64" ]
        , Ant.Icons.infoCircleFilled [ width "64", height "64" ]
        , Ant.Icons.exclamationCircleFilled [ width "64", height "64" ]
        , Ant.Icons.closeCircleFilled [ width "64", height "64" ]
        , Ant.Icons.closeSquareFilled [ width "64", height "64" ]
        , Ant.Icons.checkCircleFilled [ width "64", height "64" ]
        , Ant.Icons.checkSquareFilled [ width "64", height "64" ]
        , Ant.Icons.clockCircleFilled [ width "64", height "64" ]
        , Ant.Icons.warningFilled [ width "64", height "64" ]
        , Ant.Icons.stopFilled [ width "64", height "64" ]
        ]
    , twoTone =
        [ Ant.Icons.questionCircleTwoTone [ width "64", height "64" ]
        , Ant.Icons.plusCircleTwoTone [ width "64", height "64" ]
        , Ant.Icons.pauseCircleTwoTone [ width "64", height "64" ]
        , Ant.Icons.minusCircleTwoTone [ width "64", height "64" ]
        , Ant.Icons.plusSquareTwoTone [ width "64", height "64" ]
        , Ant.Icons.minusSquareTwoTone [ width "64", height "64" ]
        , Ant.Icons.infoCircleTwoTone [ width "64", height "64" ]
        , Ant.Icons.exclamationCircleTwoTone [ width "64", height "64" ]
        , Ant.Icons.closeCircleTwoTone [ width "64", height "64" ]
        , Ant.Icons.closeSquareTwoTone [ width "64", height "64" ]
        , Ant.Icons.checkCircleTwoTone [ width "64", height "64" ]
        , Ant.Icons.checkSquareTwoTone [ width "64", height "64" ]
        , Ant.Icons.clockCircleTwoTone [ width "64", height "64" ]
        , Ant.Icons.warningTwoTone [ width "64", height "64" ]
        , Ant.Icons.stopTwoTone [ width "64", height "64" ]
        ]
    }


editor : Category msg
editor =
    { name = "Editor Icons"
    , outlined =
        [ Ant.Icons.editOutlined [ width "64", height "64" ]
        , Ant.Icons.formOutlined [ width "64", height "64" ]
        , Ant.Icons.copyOutlined [ width "64", height "64" ]
        , Ant.Icons.scissorOutlined [ width "64", height "64" ]
        , Ant.Icons.deleteOutlined [ width "64", height "64" ]
        , Ant.Icons.snippetsOutlined [ width "64", height "64" ]
        , Ant.Icons.diffOutlined [ width "64", height "64" ]
        , Ant.Icons.highlightOutlined [ width "64", height "64" ]
        , Ant.Icons.alignCenterOutlined [ width "64", height "64" ]
        , Ant.Icons.alignLeftOutlined [ width "64", height "64" ]
        , Ant.Icons.alignRightOutlined [ width "64", height "64" ]
        , Ant.Icons.bgColorsOutlined [ width "64", height "64" ]
        , Ant.Icons.boldOutlined [ width "64", height "64" ]
        , Ant.Icons.italicOutlined [ width "64", height "64" ]
        , Ant.Icons.underlineOutlined [ width "64", height "64" ]
        , Ant.Icons.strikethroughOutlined [ width "64", height "64" ]
        , Ant.Icons.redoOutlined [ width "64", height "64" ]
        , Ant.Icons.undoOutlined [ width "64", height "64" ]
        , Ant.Icons.zoomInOutlined [ width "64", height "64" ]
        , Ant.Icons.zoomOutOutlined [ width "64", height "64" ]
        , Ant.Icons.fontColorsOutlined [ width "64", height "64" ]
        , Ant.Icons.fontSizeOutlined [ width "64", height "64" ]
        , Ant.Icons.lineHeightOutlined [ width "64", height "64" ]
        , Ant.Icons.dashOutlined [ width "64", height "64" ]
        , Ant.Icons.smallDashOutlined [ width "64", height "64" ]
        , Ant.Icons.sortAscendingOutlined [ width "64", height "64" ]
        , Ant.Icons.sortDescendingOutlined [ width "64", height "64" ]
        , Ant.Icons.dragOutlined [ width "64", height "64" ]
        , Ant.Icons.orderedListOutlined [ width "64", height "64" ]
        , Ant.Icons.unorderedListOutlined [ width "64", height "64" ]
        , Ant.Icons.radiusSettingOutlined [ width "64", height "64" ]
        , Ant.Icons.columnWidthOutlined [ width "64", height "64" ]
        , Ant.Icons.columnHeightOutlined [ width "64", height "64" ]
        ]
    , filled =
        [ Ant.Icons.editFilled [ width "64", height "64" ]
        , Ant.Icons.copyFilled [ width "64", height "64" ]
        , Ant.Icons.deleteFilled [ width "64", height "64" ]
        , Ant.Icons.snippetsFilled [ width "64", height "64" ]
        , Ant.Icons.diffFilled [ width "64", height "64" ]
        , Ant.Icons.highlightFilled [ width "64", height "64" ]
        ]
    , twoTone =
        [ Ant.Icons.editTwoTone [ width "64", height "64" ]
        , Ant.Icons.copyTwoTone [ width "64", height "64" ]
        , Ant.Icons.deleteTwoTone [ width "64", height "64" ]
        , Ant.Icons.snippetsTwoTone [ width "64", height "64" ]
        , Ant.Icons.diffTwoTone [ width "64", height "64" ]
        , Ant.Icons.highlightTwoTone [ width "64", height "64" ]
        ]
    }


data : Category msg
data =
    { name = "Data Icons"
    , outlined =
        [ Ant.Icons.areaChartOutlined [ width "64", height "64" ]
        , Ant.Icons.pieChartOutlined [ width "64", height "64" ]
        , Ant.Icons.barChartOutlined [ width "64", height "64" ]
        , Ant.Icons.dotChartOutlined [ width "64", height "64" ]
        , Ant.Icons.lineChartOutlined [ width "64", height "64" ]
        , Ant.Icons.radarChartOutlined [ width "64", height "64" ]
        , Ant.Icons.heatMapOutlined [ width "64", height "64" ]
        , Ant.Icons.fallOutlined [ width "64", height "64" ]
        , Ant.Icons.riseOutlined [ width "64", height "64" ]
        , Ant.Icons.stockOutlined [ width "64", height "64" ]
        , Ant.Icons.boxPlotOutlined [ width "64", height "64" ]
        , Ant.Icons.fundOutlined [ width "64", height "64" ]
        , Ant.Icons.slidersOutlined [ width "64", height "64" ]
        ]
    , filled =
        [ Ant.Icons.pieChartFilled [ width "64", height "64" ]
        , Ant.Icons.boxPlotFilled [ width "64", height "64" ]
        , Ant.Icons.fundFilled [ width "64", height "64" ]
        , Ant.Icons.slidersFilled [ width "64", height "64" ]
        ]
    , twoTone =
        [ Ant.Icons.pieChartTwoTone [ width "64", height "64" ]
        , Ant.Icons.boxPlotTwoTone [ width "64", height "64" ]
        , Ant.Icons.fundTwoTone [ width "64", height "64" ]
        , Ant.Icons.slidersTwoTone [ width "64", height "64" ]
        ]
    }


logo : Category msg
logo =
    { name = "Brand and Logos"
    , outlined =
        [ Ant.Icons.androidOutlined [ width "64", height "64" ]
        , Ant.Icons.appleOutlined [ width "64", height "64" ]
        , Ant.Icons.windowsOutlined [ width "64", height "64" ]
        , Ant.Icons.ieOutlined [ width "64", height "64" ]
        , Ant.Icons.chromeOutlined [ width "64", height "64" ]
        , Ant.Icons.githubOutlined [ width "64", height "64" ]
        , Ant.Icons.aliwangwangOutlined [ width "64", height "64" ]
        , Ant.Icons.dingdingOutlined [ width "64", height "64" ]
        , Ant.Icons.weiboSquareOutlined [ width "64", height "64" ]
        , Ant.Icons.weiboCircleOutlined [ width "64", height "64" ]
        , Ant.Icons.taobaoCircleOutlined [ width "64", height "64" ]
        , Ant.Icons.html5Outlined [ width "64", height "64" ]
        , Ant.Icons.weiboOutlined [ width "64", height "64" ]
        , Ant.Icons.twitterOutlined [ width "64", height "64" ]
        , Ant.Icons.wechatOutlined [ width "64", height "64" ]
        , Ant.Icons.youtubeOutlined [ width "64", height "64" ]
        , Ant.Icons.alipayCircleOutlined [ width "64", height "64" ]
        , Ant.Icons.taobaoOutlined [ width "64", height "64" ]
        , Ant.Icons.skypeOutlined [ width "64", height "64" ]
        , Ant.Icons.qqOutlined [ width "64", height "64" ]
        , Ant.Icons.mediumWorkmarkOutlined [ width "64", height "64" ]
        , Ant.Icons.gitlabOutlined [ width "64", height "64" ]
        , Ant.Icons.mediumOutlined [ width "64", height "64" ]
        , Ant.Icons.linkedinOutlined [ width "64", height "64" ]
        , Ant.Icons.googlePlusOutlined [ width "64", height "64" ]
        , Ant.Icons.dropboxOutlined [ width "64", height "64" ]
        , Ant.Icons.facebookOutlined [ width "64", height "64" ]
        , Ant.Icons.codepenOutlined [ width "64", height "64" ]
        , Ant.Icons.codeSandboxOutlined [ width "64", height "64" ]
        , Ant.Icons.amazonOutlined [ width "64", height "64" ]
        , Ant.Icons.googleOutlined [ width "64", height "64" ]
        , Ant.Icons.codepenCircleOutlined [ width "64", height "64" ]
        , Ant.Icons.alipayOutlined [ width "64", height "64" ]
        , Ant.Icons.antDesignOutlined [ width "64", height "64" ]
        , Ant.Icons.antCloudOutlined [ width "64", height "64" ]
        , Ant.Icons.aliyunOutlined [ width "64", height "64" ]
        , Ant.Icons.zhihuOutlined [ width "64", height "64" ]
        , Ant.Icons.slackOutlined [ width "64", height "64" ]
        , Ant.Icons.slackSquareOutlined [ width "64", height "64" ]
        , Ant.Icons.behanceOutlined [ width "64", height "64" ]
        , Ant.Icons.behanceSquareOutlined [ width "64", height "64" ]
        , Ant.Icons.dribbbleOutlined [ width "64", height "64" ]
        , Ant.Icons.dribbbleSquareOutlined [ width "64", height "64" ]
        , Ant.Icons.instagramOutlined [ width "64", height "64" ]
        , Ant.Icons.yuqueOutlined [ width "64", height "64" ]
        , Ant.Icons.alibabaOutlined [ width "64", height "64" ]
        , Ant.Icons.yahooOutlined [ width "64", height "64" ]
        , Ant.Icons.redditOutlined [ width "64", height "64" ]
        , Ant.Icons.sketchOutlined [ width "64", height "64" ]
        ]
    , filled =
        [ Ant.Icons.androidFilled [ width "64", height "64" ]
        , Ant.Icons.appleFilled [ width "64", height "64" ]
        , Ant.Icons.windowsFilled [ width "64", height "64" ]
        , Ant.Icons.chromeFilled [ width "64", height "64" ]
        , Ant.Icons.githubFilled [ width "64", height "64" ]
        , Ant.Icons.aliwangwangFilled [ width "64", height "64" ]
        , Ant.Icons.weiboSquareFilled [ width "64", height "64" ]
        , Ant.Icons.weiboCircleFilled [ width "64", height "64" ]
        , Ant.Icons.taobaoCircleFilled [ width "64", height "64" ]
        , Ant.Icons.html5Filled [ width "64", height "64" ]
        , Ant.Icons.wechatFilled [ width "64", height "64" ]
        , Ant.Icons.youtubeFilled [ width "64", height "64" ]
        , Ant.Icons.alipayCircleFilled [ width "64", height "64" ]
        , Ant.Icons.skypeFilled [ width "64", height "64" ]
        , Ant.Icons.gitlabFilled [ width "64", height "64" ]
        , Ant.Icons.linkedinFilled [ width "64", height "64" ]
        , Ant.Icons.facebookFilled [ width "64", height "64" ]
        , Ant.Icons.codeSandboxCircleFilled [ width "64", height "64" ]
        , Ant.Icons.codepenCircleFilled [ width "64", height "64" ]
        , Ant.Icons.slackSquareFilled [ width "64", height "64" ]
        , Ant.Icons.behanceSquareFilled [ width "64", height "64" ]
        , Ant.Icons.dribbbleSquareFilled [ width "64", height "64" ]
        , Ant.Icons.instagramFilled [ width "64", height "64" ]
        , Ant.Icons.yuqueFilled [ width "64", height "64" ]
        , Ant.Icons.yahooFilled [ width "64", height "64" ]
        ]
    , twoTone =
        [ Ant.Icons.html5TwoTone [ width "64", height "64" ]
        ]
    }


other : Category msg
other =
    { name = "Application Icons"
    , outlined =
        [ Ant.Icons.accountBookOutlined [ width "64", height "64" ]
        , Ant.Icons.aimOutlined [ width "64", height "64" ]
        , Ant.Icons.alertOutlined [ width "64", height "64" ]
        , Ant.Icons.apartmentOutlined [ width "64", height "64" ]
        , Ant.Icons.apiOutlined [ width "64", height "64" ]
        , Ant.Icons.appstoreAddOutlined [ width "64", height "64" ]
        , Ant.Icons.appstoreOutlined [ width "64", height "64" ]
        , Ant.Icons.audioOutlined [ width "64", height "64" ]
        , Ant.Icons.audioMutedOutlined [ width "64", height "64" ]
        , Ant.Icons.auditOutlined [ width "64", height "64" ]
        , Ant.Icons.bankOutlined [ width "64", height "64" ]
        , Ant.Icons.barcodeOutlined [ width "64", height "64" ]
        , Ant.Icons.barsOutlined [ width "64", height "64" ]
        , Ant.Icons.bellOutlined [ width "64", height "64" ]
        , Ant.Icons.blockOutlined [ width "64", height "64" ]
        , Ant.Icons.bookOutlined [ width "64", height "64" ]
        , Ant.Icons.borderOutlined [ width "64", height "64" ]
        , Ant.Icons.borderlessTableOutlined [ width "64", height "64" ]
        , Ant.Icons.branchesOutlined [ width "64", height "64" ]
        , Ant.Icons.bugOutlined [ width "64", height "64" ]
        , Ant.Icons.buildOutlined [ width "64", height "64" ]
        , Ant.Icons.bulbOutlined [ width "64", height "64" ]
        , Ant.Icons.calculatorOutlined [ width "64", height "64" ]
        , Ant.Icons.calendarOutlined [ width "64", height "64" ]
        , Ant.Icons.cameraOutlined [ width "64", height "64" ]
        , Ant.Icons.carOutlined [ width "64", height "64" ]
        , Ant.Icons.carryOutOutlined [ width "64", height "64" ]
        , Ant.Icons.ciCircleOutlined [ width "64", height "64" ]
        , Ant.Icons.ciOutlined [ width "64", height "64" ]
        , Ant.Icons.clearOutlined [ width "64", height "64" ]
        , Ant.Icons.cloudDownloadOutlined [ width "64", height "64" ]
        , Ant.Icons.cloudOutlined [ width "64", height "64" ]
        , Ant.Icons.cloudServerOutlined [ width "64", height "64" ]
        , Ant.Icons.cloudSyncOutlined [ width "64", height "64" ]
        , Ant.Icons.cloudUploadOutlined [ width "64", height "64" ]
        , Ant.Icons.clusterOutlined [ width "64", height "64" ]
        , Ant.Icons.codeOutlined [ width "64", height "64" ]
        , Ant.Icons.coffeeOutlined [ width "64", height "64" ]
        , Ant.Icons.commentOutlined [ width "64", height "64" ]
        , Ant.Icons.compassOutlined [ width "64", height "64" ]
        , Ant.Icons.compressOutlined [ width "64", height "64" ]
        , Ant.Icons.consoleSqlOutlined [ width "64", height "64" ]
        , Ant.Icons.contactsOutlined [ width "64", height "64" ]
        , Ant.Icons.containerOutlined [ width "64", height "64" ]
        , Ant.Icons.controlOutlined [ width "64", height "64" ]
        , Ant.Icons.copyrightCircleOutlined [ width "64", height "64" ]
        , Ant.Icons.copyrightOutlined [ width "64", height "64" ]
        , Ant.Icons.creditCardOutlined [ width "64", height "64" ]
        , Ant.Icons.crownOutlined [ width "64", height "64" ]
        , Ant.Icons.customerServiceOutlined [ width "64", height "64" ]
        , Ant.Icons.dashboardOutlined [ width "64", height "64" ]
        , Ant.Icons.databaseOutlined [ width "64", height "64" ]
        , Ant.Icons.deleteColumnOutlined [ width "64", height "64" ]
        , Ant.Icons.deleteRowOutlined [ width "64", height "64" ]
        , Ant.Icons.deliveredProcedureOutlined [ width "64", height "64" ]
        , Ant.Icons.deploymentUnitOutlined [ width "64", height "64" ]
        , Ant.Icons.desktopOutlined [ width "64", height "64" ]
        , Ant.Icons.dingtalkOutlined [ width "64", height "64" ]
        , Ant.Icons.disconnectOutlined [ width "64", height "64" ]
        , Ant.Icons.dislikeOutlined [ width "64", height "64" ]
        , Ant.Icons.dollarCircleOutlined [ width "64", height "64" ]
        , Ant.Icons.dollarOutlined [ width "64", height "64" ]
        , Ant.Icons.downloadOutlined [ width "64", height "64" ]
        , Ant.Icons.ellipsisOutlined [ width "64", height "64" ]
        , Ant.Icons.environmentOutlined [ width "64", height "64" ]
        , Ant.Icons.euroCircleOutlined [ width "64", height "64" ]
        , Ant.Icons.euroOutlined [ width "64", height "64" ]
        , Ant.Icons.exceptionOutlined [ width "64", height "64" ]
        , Ant.Icons.expandAltOutlined [ width "64", height "64" ]
        , Ant.Icons.expandOutlined [ width "64", height "64" ]
        , Ant.Icons.experimentOutlined [ width "64", height "64" ]
        , Ant.Icons.exportOutlined [ width "64", height "64" ]
        , Ant.Icons.eyeOutlined [ width "64", height "64" ]
        , Ant.Icons.eyeInvisibleOutlined [ width "64", height "64" ]
        , Ant.Icons.fieldBinaryOutlined [ width "64", height "64" ]
        , Ant.Icons.fieldNumberOutlined [ width "64", height "64" ]
        , Ant.Icons.fieldStringOutlined [ width "64", height "64" ]
        , Ant.Icons.fieldTimeOutlined [ width "64", height "64" ]
        , Ant.Icons.fileAddOutlined [ width "64", height "64" ]
        , Ant.Icons.fileDoneOutlined [ width "64", height "64" ]
        , Ant.Icons.fileExcelOutlined [ width "64", height "64" ]
        , Ant.Icons.fileExclamationOutlined [ width "64", height "64" ]
        , Ant.Icons.fileOutlined [ width "64", height "64" ]
        , Ant.Icons.fileGifOutlined [ width "64", height "64" ]
        , Ant.Icons.fileImageOutlined [ width "64", height "64" ]
        , Ant.Icons.fileJpgOutlined [ width "64", height "64" ]
        , Ant.Icons.fileMarkdownOutlined [ width "64", height "64" ]
        , Ant.Icons.filePdfOutlined [ width "64", height "64" ]
        , Ant.Icons.filePptOutlined [ width "64", height "64" ]
        , Ant.Icons.fileProtectOutlined [ width "64", height "64" ]
        , Ant.Icons.fileSearchOutlined [ width "64", height "64" ]
        , Ant.Icons.fileSyncOutlined [ width "64", height "64" ]
        , Ant.Icons.fileTextOutlined [ width "64", height "64" ]
        , Ant.Icons.fileUnknownOutlined [ width "64", height "64" ]
        , Ant.Icons.fileWordOutlined [ width "64", height "64" ]
        , Ant.Icons.fileZipOutlined [ width "64", height "64" ]
        , Ant.Icons.filterOutlined [ width "64", height "64" ]
        , Ant.Icons.fireOutlined [ width "64", height "64" ]
        , Ant.Icons.flagOutlined [ width "64", height "64" ]
        , Ant.Icons.folderAddOutlined [ width "64", height "64" ]
        , Ant.Icons.folderOutlined [ width "64", height "64" ]
        , Ant.Icons.folderOpenOutlined [ width "64", height "64" ]
        , Ant.Icons.folderViewOutlined [ width "64", height "64" ]
        , Ant.Icons.forkOutlined [ width "64", height "64" ]
        , Ant.Icons.formatPainterOutlined [ width "64", height "64" ]
        , Ant.Icons.frownOutlined [ width "64", height "64" ]
        , Ant.Icons.functionOutlined [ width "64", height "64" ]
        , Ant.Icons.fundProjectionScreenOutlined [ width "64", height "64" ]
        , Ant.Icons.fundViewOutlined [ width "64", height "64" ]
        , Ant.Icons.funnelPlotOutlined [ width "64", height "64" ]
        , Ant.Icons.gatewayOutlined [ width "64", height "64" ]
        , Ant.Icons.gifOutlined [ width "64", height "64" ]
        , Ant.Icons.giftOutlined [ width "64", height "64" ]
        , Ant.Icons.globalOutlined [ width "64", height "64" ]
        , Ant.Icons.goldOutlined [ width "64", height "64" ]
        , Ant.Icons.groupOutlined [ width "64", height "64" ]
        , Ant.Icons.hddOutlined [ width "64", height "64" ]
        , Ant.Icons.heartOutlined [ width "64", height "64" ]
        , Ant.Icons.historyOutlined [ width "64", height "64" ]
        , Ant.Icons.homeOutlined [ width "64", height "64" ]
        , Ant.Icons.hourglassOutlined [ width "64", height "64" ]
        , Ant.Icons.idcardOutlined [ width "64", height "64" ]
        , Ant.Icons.importOutlined [ width "64", height "64" ]
        , Ant.Icons.inboxOutlined [ width "64", height "64" ]
        , Ant.Icons.insertRowAboveOutlined [ width "64", height "64" ]
        , Ant.Icons.insertRowBelowOutlined [ width "64", height "64" ]
        , Ant.Icons.insertRowLeftOutlined [ width "64", height "64" ]
        , Ant.Icons.insertRowRightOutlined [ width "64", height "64" ]
        , Ant.Icons.insuranceOutlined [ width "64", height "64" ]
        , Ant.Icons.interactionOutlined [ width "64", height "64" ]
        , Ant.Icons.keyOutlined [ width "64", height "64" ]
        , Ant.Icons.laptopOutlined [ width "64", height "64" ]
        , Ant.Icons.layoutOutlined [ width "64", height "64" ]
        , Ant.Icons.likeOutlined [ width "64", height "64" ]
        , Ant.Icons.lineOutlined [ width "64", height "64" ]
        , Ant.Icons.linkOutlined [ width "64", height "64" ]
        , Ant.Icons.loading3QuartersOutlined [ width "64", height "64" ]
        , Ant.Icons.loadingOutlined [ width "64", height "64" ]
        , Ant.Icons.lockOutlined [ width "64", height "64" ]
        , Ant.Icons.macCommandOutlined [ width "64", height "64" ]
        , Ant.Icons.mailOutlined [ width "64", height "64" ]
        , Ant.Icons.manOutlined [ width "64", height "64" ]
        , Ant.Icons.medicineBoxOutlined [ width "64", height "64" ]
        , Ant.Icons.mehOutlined [ width "64", height "64" ]
        , Ant.Icons.menuOutlined [ width "64", height "64" ]
        , Ant.Icons.mergeCellsOutlined [ width "64", height "64" ]
        , Ant.Icons.messageOutlined [ width "64", height "64" ]
        , Ant.Icons.mobileOutlined [ width "64", height "64" ]
        , Ant.Icons.moneyCollectOutlined [ width "64", height "64" ]
        , Ant.Icons.monitorOutlined [ width "64", height "64" ]
        , Ant.Icons.moreOutlined [ width "64", height "64" ]
        , Ant.Icons.nodeCollapseOutlined [ width "64", height "64" ]
        , Ant.Icons.nodeExpandOutlined [ width "64", height "64" ]
        , Ant.Icons.nodeIndexOutlined [ width "64", height "64" ]
        , Ant.Icons.notificationOutlined [ width "64", height "64" ]
        , Ant.Icons.numberOutlined [ width "64", height "64" ]
        , Ant.Icons.oneToOneOutlined [ width "64", height "64" ]
        , Ant.Icons.paperClipOutlined [ width "64", height "64" ]
        , Ant.Icons.partitionOutlined [ width "64", height "64" ]
        , Ant.Icons.payCircleOutlined [ width "64", height "64" ]
        , Ant.Icons.percentageOutlined [ width "64", height "64" ]
        , Ant.Icons.phoneOutlined [ width "64", height "64" ]
        , Ant.Icons.pictureOutlined [ width "64", height "64" ]
        , Ant.Icons.playSquareOutlined [ width "64", height "64" ]
        , Ant.Icons.poundCircleOutlined [ width "64", height "64" ]
        , Ant.Icons.poundOutlined [ width "64", height "64" ]
        , Ant.Icons.poweroffOutlined [ width "64", height "64" ]
        , Ant.Icons.printerOutlined [ width "64", height "64" ]
        , Ant.Icons.profileOutlined [ width "64", height "64" ]
        , Ant.Icons.projectOutlined [ width "64", height "64" ]
        , Ant.Icons.propertySafetyOutlined [ width "64", height "64" ]
        , Ant.Icons.pullRequestOutlined [ width "64", height "64" ]
        , Ant.Icons.pushpinOutlined [ width "64", height "64" ]
        , Ant.Icons.qrcodeOutlined [ width "64", height "64" ]
        , Ant.Icons.readOutlined [ width "64", height "64" ]
        , Ant.Icons.reconciliationOutlined [ width "64", height "64" ]
        , Ant.Icons.redEnvelopeOutlined [ width "64", height "64" ]
        , Ant.Icons.reloadOutlined [ width "64", height "64" ]
        , Ant.Icons.restOutlined [ width "64", height "64" ]
        , Ant.Icons.robotOutlined [ width "64", height "64" ]
        , Ant.Icons.rocketOutlined [ width "64", height "64" ]
        , Ant.Icons.rotateLeftOutlined [ width "64", height "64" ]
        , Ant.Icons.rotateRightOutlined [ width "64", height "64" ]
        , Ant.Icons.safetyCertificateOutlined [ width "64", height "64" ]
        , Ant.Icons.safetyOutlined [ width "64", height "64" ]
        , Ant.Icons.saveOutlined [ width "64", height "64" ]
        , Ant.Icons.scanOutlined [ width "64", height "64" ]
        , Ant.Icons.scheduleOutlined [ width "64", height "64" ]
        , Ant.Icons.searchOutlined [ width "64", height "64" ]
        , Ant.Icons.securityScanOutlined [ width "64", height "64" ]
        , Ant.Icons.selectOutlined [ width "64", height "64" ]
        , Ant.Icons.sendOutlined [ width "64", height "64" ]
        , Ant.Icons.settingOutlined [ width "64", height "64" ]
        , Ant.Icons.shakeOutlined [ width "64", height "64" ]
        , Ant.Icons.shareAltOutlined [ width "64", height "64" ]
        , Ant.Icons.shopOutlined [ width "64", height "64" ]
        , Ant.Icons.shoppingCartOutlined [ width "64", height "64" ]
        , Ant.Icons.shoppingOutlined [ width "64", height "64" ]
        , Ant.Icons.sisternodeOutlined [ width "64", height "64" ]
        , Ant.Icons.skinOutlined [ width "64", height "64" ]
        , Ant.Icons.smileOutlined [ width "64", height "64" ]
        , Ant.Icons.solutionOutlined [ width "64", height "64" ]
        , Ant.Icons.soundOutlined [ width "64", height "64" ]
        , Ant.Icons.splitCellsOutlined [ width "64", height "64" ]
        , Ant.Icons.starOutlined [ width "64", height "64" ]
        , Ant.Icons.subnodeOutlined [ width "64", height "64" ]
        , Ant.Icons.switcherOutlined [ width "64", height "64" ]
        , Ant.Icons.syncOutlined [ width "64", height "64" ]
        , Ant.Icons.tableOutlined [ width "64", height "64" ]
        , Ant.Icons.tabletOutlined [ width "64", height "64" ]
        , Ant.Icons.tagOutlined [ width "64", height "64" ]
        , Ant.Icons.tagsOutlined [ width "64", height "64" ]
        , Ant.Icons.teamOutlined [ width "64", height "64" ]
        , Ant.Icons.thunderboltOutlined [ width "64", height "64" ]
        , Ant.Icons.toTopOutlined [ width "64", height "64" ]
        , Ant.Icons.toolOutlined [ width "64", height "64" ]
        , Ant.Icons.trademarkCircleOutlined [ width "64", height "64" ]
        , Ant.Icons.trademarkOutlined [ width "64", height "64" ]
        , Ant.Icons.transactionOutlined [ width "64", height "64" ]
        , Ant.Icons.translationOutlined [ width "64", height "64" ]
        , Ant.Icons.trophyOutlined [ width "64", height "64" ]
        , Ant.Icons.ungroupOutlined [ width "64", height "64" ]
        , Ant.Icons.unlockOutlined [ width "64", height "64" ]
        , Ant.Icons.uploadOutlined [ width "64", height "64" ]
        , Ant.Icons.usbOutlined [ width "64", height "64" ]
        , Ant.Icons.userAddOutlined [ width "64", height "64" ]
        , Ant.Icons.userDeleteOutlined [ width "64", height "64" ]
        , Ant.Icons.userOutlined [ width "64", height "64" ]
        , Ant.Icons.userSwitchOutlined [ width "64", height "64" ]
        , Ant.Icons.usergroupAddOutlined [ width "64", height "64" ]
        , Ant.Icons.usergroupDeleteOutlined [ width "64", height "64" ]
        , Ant.Icons.verifiedOutlined [ width "64", height "64" ]
        , Ant.Icons.videoCameraAddOutlined [ width "64", height "64" ]
        , Ant.Icons.videoCameraOutlined [ width "64", height "64" ]
        , Ant.Icons.walletOutlined [ width "64", height "64" ]
        , Ant.Icons.whatsAppOutlined [ width "64", height "64" ]
        , Ant.Icons.wifiOutlined [ width "64", height "64" ]
        , Ant.Icons.womanOutlined [ width "64", height "64" ]
        ]
    , filled =
        [ Ant.Icons.accountBookFilled [ width "64", height "64" ]
        , Ant.Icons.alertFilled [ width "64", height "64" ]
        , Ant.Icons.alipaySquareFilled [ width "64", height "64" ]
        , Ant.Icons.amazonCircleFilled [ width "64", height "64" ]
        , Ant.Icons.amazonSquareFilled [ width "64", height "64" ]
        , Ant.Icons.apiFilled [ width "64", height "64" ]
        , Ant.Icons.appstoreFilled [ width "64", height "64" ]
        , Ant.Icons.audioFilled [ width "64", height "64" ]
        , Ant.Icons.bankFilled [ width "64", height "64" ]
        , Ant.Icons.behanceCircleFilled [ width "64", height "64" ]
        , Ant.Icons.bellFilled [ width "64", height "64" ]
        , Ant.Icons.bookFilled [ width "64", height "64" ]
        , Ant.Icons.bugFilled [ width "64", height "64" ]
        , Ant.Icons.buildFilled [ width "64", height "64" ]
        , Ant.Icons.bulbFilled [ width "64", height "64" ]
        , Ant.Icons.calculatorFilled [ width "64", height "64" ]
        , Ant.Icons.calendarFilled [ width "64", height "64" ]
        , Ant.Icons.cameraFilled [ width "64", height "64" ]
        , Ant.Icons.carFilled [ width "64", height "64" ]
        , Ant.Icons.carryOutFilled [ width "64", height "64" ]
        , Ant.Icons.ciCircleFilled [ width "64", height "64" ]
        , Ant.Icons.cloudFilled [ width "64", height "64" ]
        , Ant.Icons.codeFilled [ width "64", height "64" ]
        , Ant.Icons.codeSandboxSquareFilled [ width "64", height "64" ]
        , Ant.Icons.codepenSquareFilled [ width "64", height "64" ]
        , Ant.Icons.compassFilled [ width "64", height "64" ]
        , Ant.Icons.contactsFilled [ width "64", height "64" ]
        , Ant.Icons.containerFilled [ width "64", height "64" ]
        , Ant.Icons.controlFilled [ width "64", height "64" ]
        , Ant.Icons.copyrightCircleFilled [ width "64", height "64" ]
        , Ant.Icons.creditCardFilled [ width "64", height "64" ]
        , Ant.Icons.crownFilled [ width "64", height "64" ]
        , Ant.Icons.customerServiceFilled [ width "64", height "64" ]
        , Ant.Icons.dashboardFilled [ width "64", height "64" ]
        , Ant.Icons.databaseFilled [ width "64", height "64" ]
        , Ant.Icons.dingtalkCircleFilled [ width "64", height "64" ]
        , Ant.Icons.dingtalkSquareFilled [ width "64", height "64" ]
        , Ant.Icons.dislikeFilled [ width "64", height "64" ]
        , Ant.Icons.dollarCircleFilled [ width "64", height "64" ]
        , Ant.Icons.dribbbleCircleFilled [ width "64", height "64" ]
        , Ant.Icons.dropboxCircleFilled [ width "64", height "64" ]
        , Ant.Icons.dropboxSquareFilled [ width "64", height "64" ]
        , Ant.Icons.environmentFilled [ width "64", height "64" ]
        , Ant.Icons.euroCircleFilled [ width "64", height "64" ]
        , Ant.Icons.experimentFilled [ width "64", height "64" ]
        , Ant.Icons.eyeFilled [ width "64", height "64" ]
        , Ant.Icons.eyeInvisibleFilled [ width "64", height "64" ]
        , Ant.Icons.fileAddFilled [ width "64", height "64" ]
        , Ant.Icons.fileExcelFilled [ width "64", height "64" ]
        , Ant.Icons.fileExclamationFilled [ width "64", height "64" ]
        , Ant.Icons.fileFilled [ width "64", height "64" ]
        , Ant.Icons.fileImageFilled [ width "64", height "64" ]
        , Ant.Icons.fileMarkdownFilled [ width "64", height "64" ]
        , Ant.Icons.filePdfFilled [ width "64", height "64" ]
        , Ant.Icons.filePptFilled [ width "64", height "64" ]
        , Ant.Icons.fileTextFilled [ width "64", height "64" ]
        , Ant.Icons.fileUnknownFilled [ width "64", height "64" ]
        , Ant.Icons.fileWordFilled [ width "64", height "64" ]
        , Ant.Icons.fileZipFilled [ width "64", height "64" ]
        , Ant.Icons.filterFilled [ width "64", height "64" ]
        , Ant.Icons.fireFilled [ width "64", height "64" ]
        , Ant.Icons.flagFilled [ width "64", height "64" ]
        , Ant.Icons.folderAddFilled [ width "64", height "64" ]
        , Ant.Icons.folderFilled [ width "64", height "64" ]
        , Ant.Icons.folderOpenFilled [ width "64", height "64" ]
        , Ant.Icons.formatPainterFilled [ width "64", height "64" ]
        , Ant.Icons.frownFilled [ width "64", height "64" ]
        , Ant.Icons.funnelPlotFilled [ width "64", height "64" ]
        , Ant.Icons.giftFilled [ width "64", height "64" ]
        , Ant.Icons.goldFilled [ width "64", height "64" ]
        , Ant.Icons.goldenFilled [ width "64", height "64" ]
        , Ant.Icons.googleCircleFilled [ width "64", height "64" ]
        , Ant.Icons.googlePlusCircleFilled [ width "64", height "64" ]
        , Ant.Icons.googlePlusSquareFilled [ width "64", height "64" ]
        , Ant.Icons.googleSquareFilled [ width "64", height "64" ]
        , Ant.Icons.hddFilled [ width "64", height "64" ]
        , Ant.Icons.heartFilled [ width "64", height "64" ]
        , Ant.Icons.homeFilled [ width "64", height "64" ]
        , Ant.Icons.hourglassFilled [ width "64", height "64" ]
        , Ant.Icons.idcardFilled [ width "64", height "64" ]
        , Ant.Icons.ieCircleFilled [ width "64", height "64" ]
        , Ant.Icons.ieSquareFilled [ width "64", height "64" ]
        , Ant.Icons.insuranceFilled [ width "64", height "64" ]
        , Ant.Icons.interactionFilled [ width "64", height "64" ]
        , Ant.Icons.layoutFilled [ width "64", height "64" ]
        , Ant.Icons.likeFilled [ width "64", height "64" ]
        , Ant.Icons.lockFilled [ width "64", height "64" ]
        , Ant.Icons.macCommandFilled [ width "64", height "64" ]
        , Ant.Icons.mailFilled [ width "64", height "64" ]
        , Ant.Icons.medicineBoxFilled [ width "64", height "64" ]
        , Ant.Icons.mediumCircleFilled [ width "64", height "64" ]
        , Ant.Icons.mediumSquareFilled [ width "64", height "64" ]
        , Ant.Icons.mehFilled [ width "64", height "64" ]
        , Ant.Icons.messageFilled [ width "64", height "64" ]
        , Ant.Icons.mobileFilled [ width "64", height "64" ]
        , Ant.Icons.moneyCollectFilled [ width "64", height "64" ]
        , Ant.Icons.notificationFilled [ width "64", height "64" ]
        , Ant.Icons.payCircleFilled [ width "64", height "64" ]
        , Ant.Icons.phoneFilled [ width "64", height "64" ]
        , Ant.Icons.pictureFilled [ width "64", height "64" ]
        , Ant.Icons.playSquareFilled [ width "64", height "64" ]
        , Ant.Icons.poundCircleFilled [ width "64", height "64" ]
        , Ant.Icons.printerFilled [ width "64", height "64" ]
        , Ant.Icons.profileFilled [ width "64", height "64" ]
        , Ant.Icons.projectFilled [ width "64", height "64" ]
        , Ant.Icons.propertySafetyFilled [ width "64", height "64" ]
        , Ant.Icons.pushpinFilled [ width "64", height "64" ]
        , Ant.Icons.qqCircleFilled [ width "64", height "64" ]
        , Ant.Icons.qqSquareFilled [ width "64", height "64" ]
        , Ant.Icons.readFilled [ width "64", height "64" ]
        , Ant.Icons.reconciliationFilled [ width "64", height "64" ]
        , Ant.Icons.redEnvelopeFilled [ width "64", height "64" ]
        , Ant.Icons.redditCircleFilled [ width "64", height "64" ]
        , Ant.Icons.redditSquareFilled [ width "64", height "64" ]
        , Ant.Icons.restFilled [ width "64", height "64" ]
        , Ant.Icons.robotFilled [ width "64", height "64" ]
        , Ant.Icons.rocketFilled [ width "64", height "64" ]
        , Ant.Icons.safetyCertificateFilled [ width "64", height "64" ]
        , Ant.Icons.saveFilled [ width "64", height "64" ]
        , Ant.Icons.scheduleFilled [ width "64", height "64" ]
        , Ant.Icons.securityScanFilled [ width "64", height "64" ]
        , Ant.Icons.settingFilled [ width "64", height "64" ]
        , Ant.Icons.shopFilled [ width "64", height "64" ]
        , Ant.Icons.shoppingFilled [ width "64", height "64" ]
        , Ant.Icons.signalFilled [ width "64", height "64" ]
        , Ant.Icons.sketchCircleFilled [ width "64", height "64" ]
        , Ant.Icons.sketchSquareFilled [ width "64", height "64" ]
        , Ant.Icons.skinFilled [ width "64", height "64" ]
        , Ant.Icons.slackCircleFilled [ width "64", height "64" ]
        , Ant.Icons.smileFilled [ width "64", height "64" ]
        , Ant.Icons.soundFilled [ width "64", height "64" ]
        , Ant.Icons.starFilled [ width "64", height "64" ]
        , Ant.Icons.switcherFilled [ width "64", height "64" ]
        , Ant.Icons.tabletFilled [ width "64", height "64" ]
        , Ant.Icons.tagFilled [ width "64", height "64" ]
        , Ant.Icons.tagsFilled [ width "64", height "64" ]
        , Ant.Icons.taobaoSquareFilled [ width "64", height "64" ]
        , Ant.Icons.thunderboltFilled [ width "64", height "64" ]
        , Ant.Icons.toolFilled [ width "64", height "64" ]
        , Ant.Icons.trademarkCircleFilled [ width "64", height "64" ]
        , Ant.Icons.trophyFilled [ width "64", height "64" ]
        , Ant.Icons.twitterCircleFilled [ width "64", height "64" ]
        , Ant.Icons.twitterSquareFilled [ width "64", height "64" ]
        , Ant.Icons.unlockFilled [ width "64", height "64" ]
        , Ant.Icons.usbFilled [ width "64", height "64" ]
        , Ant.Icons.videoCameraFilled [ width "64", height "64" ]
        , Ant.Icons.walletFilled [ width "64", height "64" ]
        , Ant.Icons.zhihuCircleFilled [ width "64", height "64" ]
        , Ant.Icons.zhihuSquareFilled [ width "64", height "64" ]
        ]
    , twoTone =
        [ Ant.Icons.accountBookTwoTone [ width "64", height "64" ]
        , Ant.Icons.alertTwoTone [ width "64", height "64" ]
        , Ant.Icons.apiTwoTone [ width "64", height "64" ]
        , Ant.Icons.appstoreTwoTone [ width "64", height "64" ]
        , Ant.Icons.audioTwoTone [ width "64", height "64" ]
        , Ant.Icons.bankTwoTone [ width "64", height "64" ]
        , Ant.Icons.bellTwoTone [ width "64", height "64" ]
        , Ant.Icons.bookTwoTone [ width "64", height "64" ]
        , Ant.Icons.bugTwoTone [ width "64", height "64" ]
        , Ant.Icons.buildTwoTone [ width "64", height "64" ]
        , Ant.Icons.bulbTwoTone [ width "64", height "64" ]
        , Ant.Icons.calculatorTwoTone [ width "64", height "64" ]
        , Ant.Icons.calendarTwoTone [ width "64", height "64" ]
        , Ant.Icons.cameraTwoTone [ width "64", height "64" ]
        , Ant.Icons.carTwoTone [ width "64", height "64" ]
        , Ant.Icons.carryOutTwoTone [ width "64", height "64" ]
        , Ant.Icons.ciCircleTwoTone [ width "64", height "64" ]
        , Ant.Icons.ciTwoTone [ width "64", height "64" ]
        , Ant.Icons.cloudTwoTone [ width "64", height "64" ]
        , Ant.Icons.codeTwoTone [ width "64", height "64" ]
        , Ant.Icons.compassTwoTone [ width "64", height "64" ]
        , Ant.Icons.contactsTwoTone [ width "64", height "64" ]
        , Ant.Icons.containerTwoTone [ width "64", height "64" ]
        , Ant.Icons.controlTwoTone [ width "64", height "64" ]
        , Ant.Icons.copyrightCircleTwoTone [ width "64", height "64" ]
        , Ant.Icons.copyrightTwoTone [ width "64", height "64" ]
        , Ant.Icons.creditCardTwoTone [ width "64", height "64" ]
        , Ant.Icons.crownTwoTone [ width "64", height "64" ]
        , Ant.Icons.customerServiceTwoTone [ width "64", height "64" ]
        , Ant.Icons.dashboardTwoTone [ width "64", height "64" ]
        , Ant.Icons.databaseTwoTone [ width "64", height "64" ]
        , Ant.Icons.dislikeTwoTone [ width "64", height "64" ]
        , Ant.Icons.dollarCircleTwoTone [ width "64", height "64" ]
        , Ant.Icons.dollarTwoTone [ width "64", height "64" ]
        , Ant.Icons.environmentTwoTone [ width "64", height "64" ]
        , Ant.Icons.euroCircleTwoTone [ width "64", height "64" ]
        , Ant.Icons.euroTwoTone [ width "64", height "64" ]
        , Ant.Icons.experimentTwoTone [ width "64", height "64" ]
        , Ant.Icons.eyeTwoTone [ width "64", height "64" ]
        , Ant.Icons.eyeInvisibleTwoTone [ width "64", height "64" ]
        , Ant.Icons.fileAddTwoTone [ width "64", height "64" ]
        , Ant.Icons.fileExcelTwoTone [ width "64", height "64" ]
        , Ant.Icons.fileExclamationTwoTone [ width "64", height "64" ]
        , Ant.Icons.fileTwoTone [ width "64", height "64" ]
        , Ant.Icons.fileImageTwoTone [ width "64", height "64" ]
        , Ant.Icons.fileMarkdownTwoTone [ width "64", height "64" ]
        , Ant.Icons.filePdfTwoTone [ width "64", height "64" ]
        , Ant.Icons.filePptTwoTone [ width "64", height "64" ]
        , Ant.Icons.fileTextTwoTone [ width "64", height "64" ]
        , Ant.Icons.fileUnknownTwoTone [ width "64", height "64" ]
        , Ant.Icons.fileWordTwoTone [ width "64", height "64" ]
        , Ant.Icons.fileZipTwoTone [ width "64", height "64" ]
        , Ant.Icons.filterTwoTone [ width "64", height "64" ]
        , Ant.Icons.fireTwoTone [ width "64", height "64" ]
        , Ant.Icons.flagTwoTone [ width "64", height "64" ]
        , Ant.Icons.folderAddTwoTone [ width "64", height "64" ]
        , Ant.Icons.folderTwoTone [ width "64", height "64" ]
        , Ant.Icons.folderOpenTwoTone [ width "64", height "64" ]
        , Ant.Icons.frownTwoTone [ width "64", height "64" ]
        , Ant.Icons.funnelPlotTwoTone [ width "64", height "64" ]
        , Ant.Icons.giftTwoTone [ width "64", height "64" ]
        , Ant.Icons.goldTwoTone [ width "64", height "64" ]
        , Ant.Icons.hddTwoTone [ width "64", height "64" ]
        , Ant.Icons.heartTwoTone [ width "64", height "64" ]
        , Ant.Icons.homeTwoTone [ width "64", height "64" ]
        , Ant.Icons.hourglassTwoTone [ width "64", height "64" ]
        , Ant.Icons.idcardTwoTone [ width "64", height "64" ]
        , Ant.Icons.insuranceTwoTone [ width "64", height "64" ]
        , Ant.Icons.interactionTwoTone [ width "64", height "64" ]
        , Ant.Icons.layoutTwoTone [ width "64", height "64" ]
        , Ant.Icons.likeTwoTone [ width "64", height "64" ]
        , Ant.Icons.lockTwoTone [ width "64", height "64" ]
        , Ant.Icons.mailTwoTone [ width "64", height "64" ]
        , Ant.Icons.medicineBoxTwoTone [ width "64", height "64" ]
        , Ant.Icons.mehTwoTone [ width "64", height "64" ]
        , Ant.Icons.messageTwoTone [ width "64", height "64" ]
        , Ant.Icons.mobileTwoTone [ width "64", height "64" ]
        , Ant.Icons.moneyCollectTwoTone [ width "64", height "64" ]
        , Ant.Icons.notificationTwoTone [ width "64", height "64" ]
        , Ant.Icons.phoneTwoTone [ width "64", height "64" ]
        , Ant.Icons.pictureTwoTone [ width "64", height "64" ]
        , Ant.Icons.playSquareTwoTone [ width "64", height "64" ]
        , Ant.Icons.poundCircleTwoTone [ width "64", height "64" ]
        , Ant.Icons.printerTwoTone [ width "64", height "64" ]
        , Ant.Icons.profileTwoTone [ width "64", height "64" ]
        , Ant.Icons.projectTwoTone [ width "64", height "64" ]
        , Ant.Icons.propertySafetyTwoTone [ width "64", height "64" ]
        , Ant.Icons.pushpinTwoTone [ width "64", height "64" ]
        , Ant.Icons.reconciliationTwoTone [ width "64", height "64" ]
        , Ant.Icons.redEnvelopeTwoTone [ width "64", height "64" ]
        , Ant.Icons.restTwoTone [ width "64", height "64" ]
        , Ant.Icons.rocketTwoTone [ width "64", height "64" ]
        , Ant.Icons.safetyCertificateTwoTone [ width "64", height "64" ]
        , Ant.Icons.saveTwoTone [ width "64", height "64" ]
        , Ant.Icons.scheduleTwoTone [ width "64", height "64" ]
        , Ant.Icons.securityScanTwoTone [ width "64", height "64" ]
        , Ant.Icons.settingTwoTone [ width "64", height "64" ]
        , Ant.Icons.shopTwoTone [ width "64", height "64" ]
        , Ant.Icons.shoppingTwoTone [ width "64", height "64" ]
        , Ant.Icons.skinTwoTone [ width "64", height "64" ]
        , Ant.Icons.smileTwoTone [ width "64", height "64" ]
        , Ant.Icons.soundTwoTone [ width "64", height "64" ]
        , Ant.Icons.starTwoTone [ width "64", height "64" ]
        , Ant.Icons.switcherTwoTone [ width "64", height "64" ]
        , Ant.Icons.tabletTwoTone [ width "64", height "64" ]
        , Ant.Icons.tagTwoTone [ width "64", height "64" ]
        , Ant.Icons.tagsTwoTone [ width "64", height "64" ]
        , Ant.Icons.thunderboltTwoTone [ width "64", height "64" ]
        , Ant.Icons.toolTwoTone [ width "64", height "64" ]
        , Ant.Icons.trademarkCircleTwoTone [ width "64", height "64" ]
        , Ant.Icons.trophyTwoTone [ width "64", height "64" ]
        , Ant.Icons.unlockTwoTone [ width "64", height "64" ]
        , Ant.Icons.usbTwoTone [ width "64", height "64" ]
        , Ant.Icons.videoCameraTwoTone [ width "64", height "64" ]
        , Ant.Icons.walletTwoTone [ width "64", height "64" ]
        ]
    }
